version: 2
jobs:
  make_test:
    docker:
      - image: circleci/node:12.8
    steps:
      - checkout
      - run:
          name: yarn install
          command: yarn install
      - run:
          name: yarn make
          command: yarn make
  deploy_master:
    docker:
      - image: circleci/node:12.8
    steps:
      - add_ssh_keys:
          fingerprints:
            - $FINGERPRINT_GITHUB
      - run:
          name : set answer 'yes' on git clone
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: clone green-turtle
          command: git clone https://github.com/basd4g/green-turtle.git
      - run:
          name: clone green-turtle-article
          command: git clone git@github.com:basd4g/green-turtle-article.git
      - run:
          name: mv articles
          command: rm -rf green-turtle/assets && mkdir -p green-turtle/assets/article && mv green-turtle-article/* green-turtle/assets/article
      - run:
          name: yarn install
          command: cd green-turtle && yarn install
      - run:
          name: yarn make
          command: cd green-turtle && yarn make
      - run:
          name: yarn deploy
          command: cd green-turtle && yarn deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  workflow:
    jobs:
      - deploy_master:
          filters:
            branches:
              only: master

workflows:
  version: 2
  workflow:
    jobs:
      - make_test:
          filters:
            branches:
              ignore: master
      - deploy_master:
          filters:
            branches:
              only: master
