version: 2
jobs:
  deploy_master:
    docker:
      - image: circleci/node:10.7
    steps:
      - checkout
      - run:
          name: yarn install
          command: yarn install
      - run:
          name: yarn make
          command: yarn make
      - run:
          name: yarn deploy
          command: yarn deploy --token=$FIREBASE_TOKEN
  make_test:
    docker:
      - image: circleci/node:10.7
    steps:
      - run:
          name: yarn install
          command: yarn install
      - run:
          name: yarn make
          command: yarn make
        

workflows:
  version: 2
  workflow:
    jobs:
      - make_test:
      - deploy_master:
          filters:
            branches:
              only: master
